Issue 354/support dynamic issuer in tls cert issuer logic
plabayo/rama pull request #365
Opened 2024-12-17 18:56 UTC by soundofspace

2025-01-12 18:46 UTC, GlenDC requested changes

2025-01-12 18:46 UTC, GlenDC commented on examples/tls_boring_dynamic_certs.rs
> +// TODO docs
```suggestion
```

?

2025-01-12 18:46 UTC, GlenDC commented on examples/tls_boring_dynamic_certs.rs
> +            std::str::from_utf8(include_bytes!("./assets/example.com.key"))
Seems you want to use include_str! instead

2025-01-12 18:46 UTC, GlenDC commented on examples/tls_boring_dynamic_certs.rs
> +            "hello client, you were served by boring tls terminator proxy issuing a dynamic certificate\r\n"
Pretty certain you can just call into_response() on the &'static str. Why the newlines btw?

2025-01-12 18:46 UTC, GlenDC commented on rama-net/src/tls/server/config.rs
> +    pub disable_cache_for_dynamic_issuer: bool,
Might want to replace these 2 properties with:

```
enum CacheKind {
     MemCache {
        max_size: u64
     }
     Disabled,
}
```

With default implemented as Self::MemCache { max_size: 0 } }

Something like that. Wdyt?

2025-01-12 18:46 UTC, GlenDC commented on rama-net/src/tls/server/config.rs
> +    pub fn from_dynamic_issuer<T: DynamicCertIssuer + Send + Sync + 'static>(issuer: T) -> Self {
Probably best to instead just set the SS'S trait bounds enforced on the DynamicCertIssuer already, similar to Service.

I imagine we can globally be more clever about this in a year or two, but for now this is what it is

2025-01-12 18:46 UTC, GlenDC commented on rama-net/src/tls/server/config.rs
> +    }
Is there a reason to not dynamically impl it if and only if dyn-issuer == Debug?

2025-01-12 18:46 UTC, GlenDC commented on rama-net/src/tls/server/config.rs
> +/// See trait DynService<S, Request> for more info about this pattern.
Can you link to it using markdown links, you can do so using rust mod syntax etc

2025-01-12 18:46 UTC, GlenDC commented on rama-net/src/tls/server/config.rs
> +
```suggestion
```

?

2025-01-12 18:46 UTC, GlenDC commented on rama-tls/src/boring/server/service.rs
> +            .then_some(Arc::new(Mutex::new(None)));
Why did you go for an arc-mutex instead of a oneshot channel? Is it ever expected then to be set more then once? You can only do one successful handshake for a single conn, or am I missing something?

2025-01-12 18:47 UTC, GlenDC commented
> Not ready yet still needs some cleanup all over the place

Is this still the case, or out of date PR description @soundofspace ?

2025-01-12 19:06 UTC, soundofspace commented on rama-net/src/tls/server/config.rs
> +    pub disable_cache_for_dynamic_issuer: bool,
Yea will be cleaner to use, doesn't it in that case also make more sense to set max_size to 8096, so the 0 is not treated as a default, but instead we set the default directly

2025-01-12 19:24 UTC, GlenDC commented on rama-net/src/tls/server/config.rs
> +    pub disable_cache_for_dynamic_issuer: bool,
I was thinking about that as well, but unless you use something like an u64 but that cannot ever be 0, you would anyway do that default size fallback later as well, in which case you have duplicate logic that can get out of sync

2025-01-12 19:26 UTC, GlenDC commented on rama-net/src/tls/server/config.rs
> +    pub disable_cache_for_dynamic_issuer: bool,
Eg https://doc.rust-lang.org/std/num/type.NonZeroU64.html

2025-01-12 19:30 UTC, soundofspace commented on rama-net/src/tls/server/config.rs
> +    pub disable_cache_for_dynamic_issuer: bool,
Yea was thinking about using a non zero variant to indeed force correct usage

2025-01-12 19:34 UTC, GlenDC commented on rama-net/src/tls/server/config.rs
> +    pub disable_cache_for_dynamic_issuer: bool,
Amazing, aligned we are.

2025-01-12 19:36 UTC, GlenDC commented on rama-tls/src/boring/server/acceptor_data.rs
> +        maybe_client_hello: &Option<Arc<Mutex<Option<RamaClientHello>>>>,
This would be `maybe_client_hello: Option<oneshot::Sender<RamaClientHello>>`

2025-01-12 19:38 UTC, soundofspace commented on rama-tls/src/boring/server/service.rs
> +            .then_some(Arc::new(Mutex::new(None)));
Mainly because this logic was ported from the old approach, which used arc for this. Will check if a oneshot channel makes more sense, but will need to confirm this as some of these callbacks can be called multiple times (but pretty sure that the ones we currently use are only called once)

2025-01-12 19:39 UTC, soundofspace commented on rama-net/src/tls/server/config.rs
> +    }
What exactly do you mean with this?

2025-01-12 19:40 UTC, GlenDC commented on rama-tls/src/boring/server/acceptor_data.rs
> +                "boring: no host found in server_name or ctx: defaulting to 'localhost'"
Not your design choice, I know I already did this but I wonder if this is ever expected or desired... Seems like a footgun now that I think about it. I mean if you do want localhost seems like not an issue to let them explicitly choose that?

2025-01-12 19:42 UTC, GlenDC commented on rama-net/src/tls/server/config.rs
> +    }
Sorry my bad, didn't make any sense what i wanted in the first place. Let's keep it like you have for now.

2025-01-12 19:44 UTC, GlenDC commented on tests/integration/examples/example_tests/tls_boring_dynamic_certs.rs
> +            "../../../../examples/assets/example.com.crt"
Is there a good reason why you have these as crt/keys instead of just using the easy to use Self-Signed logic that's already in there? If it is because we currently don't expose it to be used as a stand-alone thing, it might make sense to do so as part of this PR as I would prefer not having to check in crt/key pairs if I can avoid it.

2025-01-12 19:46 UTC, soundofspace commented on rama-tls/src/boring/server/acceptor_data.rs
> +                "boring: no host found in server_name or ctx: defaulting to 'localhost'"
Not sure about this, having this default to localhost does make sense to me as long as `server_name: Option<Host>` is an option. Making this just a `Host` would solve this problem, but would move "defaulting" up one layer, or we could require setting a host all the way up, just not sure what is ideal here

2025-01-12 19:49 UTC, soundofspace commented on tests/integration/examples/example_tests/tls_boring_dynamic_certs.rs
> +            "../../../../examples/assets/example.com.crt"
Main reason here to add them as files, is because I didn't find a way to import functions/constants from the examples logic in an easy way. Any tips here are welcome

2025-01-12 19:49 UTC, GlenDC commented on rama-tls/src/boring/server/acceptor_data.rs
> +                "boring: no host found in server_name or ctx: defaulting to 'localhost'"
yeah but that doesn't work given you also allow the ssl_ref path... so not sure either. We can keep it for now like this, but something to be kept in mind.

2025-01-12 19:51 UTC, GlenDC commented on tests/integration/examples/example_tests/tls_boring_dynamic_certs.rs
> +            "../../../../examples/assets/example.com.crt"
Ah.. right... Ok that does make sense. Fair enough, you can keep it like this. Only thing I can think of is to work via an intermediate test-utils crate but feels like a lot of effort for little gain.

2025-01-14 07:48 UTC, soundofspace commented on tests/integration/examples/example_tests/tls_boring_dynamic_certs.rs
> +            "../../../../examples/assets/example.com.crt"
Yea this is something I do plan to revise once we start thinking how we can make these examples smarter and more scalable, while still keeping them simple and easy to use examples.

2025-01-25 09:08 UTC, soundofspace commented on rama-tls/src/boring/server/service.rs
> +            .then_some(Arc::new(Mutex::new(None)));
Was indeed because callbacks can be called multiple times. Left a note and we can reconsider this approach once we merge boringssl bindings

2025-01-25 21:56 UTC, GlenDC approved these changes
Given how the current state of rama-tls is I think this is outstanding work @soundofspace .

However it also really shows that we learned a lot about the TLS interfaces from the work done for getting to this current implementation. Looking forward to seriously revisiting the tls story in rama. Happy that you want to drive that as well!

2025-01-25 21:58 UTC, merged